sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t Arch-Aldebaran/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true Arch-Aldebaran/docker-react npm run test